### ISSUE TITLE
Build AOSP14 for Xperia5 V fails with error: use of undeclared identifier 'compress_set_codec_params'

### ISSUE THREAD

**Issue by ziggutas** [sonyxperiadev/bug_tracker#848]
**Platform:yodo** 
**Device: Xperia5 V, XQDE-54 (pdx237)** 
**Kernel version:** 
**Android version:14** 
**Software binaries version:** 

**Previously working on**
I've never had a build complete for aosp14.
**Description**
I'm following the build instructions to "Build AOSP Android 14" and have tried userdebug first and now eng with  `lunch aosp_xqde54-ap2a-eng`.

Build promptly fails with Timekeep error which can be fixed with #837 Thanks to MarijnS95!

Build proceeds a bit then fails with:
error: ninja: 'device/sony/pdx237/rootdir/vendor/etc/resourcemanager_kalama_qrd.xml', needed by 'out/target/product/pdx237/vendor/etc/resourcemanager_kalama_qrd.xml', missing and no known rule to make it

In that directory there is "resourcemanager_kalama_**g**rd.xml" suggesting that perhaps it's a typo, although there's no way for me to be sure. Anyway I checked against the same location for the Xperia1 V  pdx234 (also yodo) and it had only the qrd.xml, so I edited the filename a tried again.

Build proceeded for an hour or so and failed again:
vendor/qcom/opensource/pal/session/src/SessionAlsaCompress.cpp:2122:30: error: use of undeclared identifier 'compress_set_codec_params'
 2122 |                     status = compress_set_codec_params(compress, &codec);

I've had a look in that file at line 2122 but I don't have the skills to understand it sadly, so I'm stuck. Is there anything to be done to get things going again?

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.
 

[error.4.log](https://github.com/user-attachments/files/17310724/error.4.log)

[SessionAlsaCompress.txt](https://github.com/user-attachments/files/17310787/SessionAlsaCompress.txt)

**Comment by bartcubbins** [comment]
I will send patches this weekend

**Comment by ziggutas** [comment]
Whilst it would be nice to complete the build I discovered there are no android14 yodo SW binaries available, so testing on the device is not possible at the moment anyway. See #849

**Comment by EisregenHaha** [comment]
by the way, i had the same problem but i didnt solve it the same way. renaming files i mostly not what you wanna do, instead change what its calling in device.mk. didnt encounter your problem

**Comment by ziggutas** [comment]
Thanks for the insight; I renamed it back and changed it device.mk. Makes sense, I just got the wrong end of the stick, lol.
The last error still stands though.

**Comment by EisregenHaha** [comment]
> Thanks for the insight; I renamed it back and changed it device.mk. Makes sense, I just got the wrong end of the stick, lol. The last error still stands though.

oh i think i know why i didnt have the issue, i just deleted the qcom manifest in which the directory is being synced from because i tried building statixos which already has qcom hal/stuff in their source. thats a solution which you obviously cant take since you are building stock aosp. cant help there then man, sorry.

**Comment by EisregenHaha** [comment]
> > Thanks for the insight; I renamed it back and changed it device.mk. Makes sense, I just got the wrong end of the stick, lol. The last error still stands though.
> 
> oh i think i know why i didnt have the issue, i just deleted the qcom manifest in which the directory is being synced from because i tried building statixos which already has qcom hal/stuff in their source. thats a solution which you obviously cant take since you are building stock aosp. cant help there then man, sorry.
> 
> you would probably need to do something similar to [this](https://github.com/MinusOS-AOSP/external_tinycompress/commit/77986ae78c1e7d4d710ad1d32c7fa24f6d656fd2) ? not sure though im just blabbering here

**Comment by EisregenHaha** [comment]
> Thanks for the update, the build now proceeds, reaching 95% before failing with another issue reported in the bugtracker: #838

change the target level from 4 to 5 in the device/sony/common/vintf/manifest.xml file (its in the first line)

**Comment by ziggutas** [comment]
Yes, I get that. The bit I struggle with is after:
" I also noticed that nothing appears to be installing the vendor_framework_compatibility_matrix.xml file located in vendor/qcom/opensource/core-utils and adding that to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE solves quite many of the issues left after changing the target-leve..."
It's out of my depth.
hardware/interfaces/compatibility_matrices/Android.mk
 I can see a section for DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE in hardware/interfaces/compatibility_matrices/Android.mk, but don't know how to "add" anything, or what, to it.

**Comment by ziggutas** [comment]
Thanks @EisregenHaha , I did that but the end result is the same. Think I'll ask in the other issue although I'm close to giving up also. 

What's the 6hrs all about? 10 mins with newflasher. Or you could lock bootloader after emma and install latest 14 with xperia companion.

Anyhow, thanks again.

**Comment by EisregenHaha** [comment]
> Thanks @EisregenHaha , I did that but the end result is the same. Think I'll ask in the other issue although I'm close to giving up also.
> 
> What's the 6hrs all about? 10 mins with newflasher. Or you could lock bootloader after emma and install latest 14 with xperia companion.
> 
> Anyhow, thanks again.

newsflasher doesnt work for me from 13->14 directly, i have to use emma, lock bl and the do every incremental update for 6 hours. i didnt know about that xperia companion thing though might check it out. also just to confirm my suspicion, you dont have the hardware/qcom-caf directory right?

**Comment by ziggutas** [comment]
> newsflasher doesnt work for me from 13->14 directly, i have to use emma, lock bl and the do every incremental update for 6 hours. i didnt know about that xperia companion thing though might check it out. also just to confirm my suspicion, you dont have the hardware/qcom-caf directory right?

That's right,  no qcom-caf dir.

Wait a minute though, you get updates after relocking? I thought it was impossible to get updates ever again. And strange you can't newflash 14. I know it doesn't work if you are on slot-b when flashing; it won't boot. That's documented in munjeni's thread on xda. I'd be tempted to sell mine if it could get updates, lol.

**Comment by EisregenHaha** [comment]
> > newsflasher doesnt work for me from 13->14 directly, i have to use emma, lock bl and the do every incremental update for 6 hours. i didnt know about that xperia companion thing though might check it out. also just to confirm my suspicion, you dont have the hardware/qcom-caf directory right?
> 
> That's right, no qcom-caf dir.
> 
> Wait a minute though, you get updates after relocking? I thought it was impossible to get updates ever again. And strange you can't newflash 14. I know it doesn't work if you are on slot-b when flashing; it won't boot. That's documented in munjeni's thread on xda. I'd be tempted to sell mine if it could get updates, lol.

yup just relock and you will get updates again and i think even the drm key restores but im not sure. you would have to check if the system id resets to being not 10 characters and netflix works or similar. without drm keys selling would be a bit shady but updates definitely work.

**Comment by EisregenHaha** [comment]
> > newsflasher doesnt work for me from 13->14 directly, i have to use emma, lock bl and the do every incremental update for 6 hours. i didnt know about that xperia companion thing though might check it out. also just to confirm my suspicion, you dont have the hardware/qcom-caf directory right?
> 
> That's right, no qcom-caf dir.
> 
> Wait a minute though, you get updates after relocking? I thought it was impossible to get updates ever again. And strange you can't newflash 14. I know it doesn't work if you are on slot-b when flashing; it won't boot. That's documented in munjeni's thread on xda. I'd be tempted to sell mine if it could get updates, lol.

Also i have another idea, do everything as i said but change the line in boardonfig to this:

https://catbin.sh/b/837c4039

if that doesnt work send me the error please

**Comment by ziggutas** [comment]
Nice one, that did it! Saves me displaying my ignorance in that other bugreport, so thanks for that. 
I'll flash it shortly and let you know if it boots or not.

**Comment by EisregenHaha** [comment]
> Nice one, that did it! Saves me displaying my ignorance in that other bugreport, so thanks for that. I'll flash it shortly and let you know if it boots or not.

hopefully it does, then i at least know that it was my fault by using a custom rom instead of aosp to build

**Comment by ziggutas** [comment]
No, it's not booting; sticking on the sony splash screen. Tried factory reset in recovery, no different.
I'm done for today, will update tomorrow.

**Comment by EisregenHaha** [comment]
> No, it's not booting; sticking on the sony splash screen. Tried factory reset in recovery, no different. I'm done for today, will update tomorrow.

oof unlucky, i gotta say for a device thats supposedly supported and a project thats only supposed to do one thing and that is make aosp buildable, its not really looking good. you flashed the A13 blobs right? because the person who fixed the typo also said those are bootable but so far i havent had any luck with anything. and btw newflasher wont fix this brick, you gotta use emma in my experience

**Comment by bartcubbins** [comment]
I will look at the fragments when I have the opportunity. Your device does not boot due to incorrect VINTF configuration

**Comment by EisregenHaha** [comment]
> I will look at the fragments when I have the opportunity. Your device does not boot due to incorrect VINTF configuration

thanks, i just saw the approach of changing the target level to 5 was wrong entirely, my b

**Comment by EisregenHaha** [comment]
> I will look at the fragments when I have the opportunity. Your device does not boot due to incorrect VINTF configuration

any luck with that?

**Comment by bartcubbins** [comment]
On it right now, deeply sorry for the delay

**Comment by EisregenHaha** [comment]
> On it right now, deeply sorry for the delay

completely fine, no need to apologize. was just interested

**Comment by bartcubbins** [comment]
Starting with A14 r50 Google made a change[1] that removed compatibility matrix 4. Now I have updated to version 5, and while you wait, as a temporary solution, you can roll back to the previous version android-14.0.0_r34. It should compile and boot

[1] https://android.googlesource.com/platform/hardware/interfaces/+/7ad5797272c40c2b83b0df5a57a0f248a210091b

**Comment by EisregenHaha** [comment]
> Starting with A14 r50 Google made a change[1] that removed compatibility matrix 4. Now I have updated to version 5, and while you wait, as a temporary solution, you can roll back to the previous version android-14.0.0_r34. It should compile and boot
> 
> [1] https://android.googlesource.com/platform/hardware/interfaces/+/7ad5797272c40c2b83b0df5a57a0f248a210091b

thanks, @ziggutas could you be the test sheep pretty please 👉👈🥺 if i have to use emma one more time im gonna kms

**Comment by rinigus** [comment]
I have been running into exactly the same issues on nagara. Will test on that and see if it will build and boot with aosp13 blobs.

**Comment by ziggutas** [comment]
Thank you @bartcubbins I'll give that a go and post back any findings. 
@EisregenHaha you can put that rope away now. Don't forget where you put it though...

**Comment by rinigus** [comment]
for me, `repo sync` fails on 

```
error: Cannot fetch platform/prebuilts/remoteexecution-client from https://android.googlesource.com/platform/prebuilts/remoteexecution-client
```

if I remove that project using local_manifests/untracked.xml, build fails quite fast with

```
source build/envsetup.sh && lunch aosp_xqct54-ap1a-userdebug
make -j$(nproc)

...
[100% 140/140] analyzing Android.bp files and generating ninja file at out/soong/build.aosp_xqct54.ninja
FAILED: out/soong/build.aosp_xqct54.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.aosp_xqct54.variables -o out/soong/build.aosp_xqct54.ninja --globListDir aosp_xqct54 --globFile out/soong/globs-aosp_xqct54.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.aosp_xqct54.build Android.bp
error: art/test/Android.run-test.bp:133:1: "art-run-test-host-data-shard06-tmp" depends on undefined module "rewrapper".
Or did you mean ["logwrapper"]?
error: art/test/Android.run-test.bp:4282:1: "art-run-test-target-data-shard88-tmp" depends on undefined module "rewrapper".
Or did you mean ["logwrapper"]?
error: art/test/Android.run-test.bp:5431:1: "art-run-test-jvm-data-shard20-tmp" depends on undefined module "rewrapper".
Or did you mean ["logwrapper"]?

```

**Comment by bartcubbins** [comment]
Just managed to boot r55. I will prepare the patches and PR them
<details>
<summary>Photo</summary>
<img src="https://github.com/user-attachments/assets/fe2fce71-7504-420f-990c-6b2bcc874f7d">
</details>

**Comment by rinigus** [comment]
I have made a mistake while setting up  android-14.0.0_r34 builds. Its building now and the same error is not there. Sorry for noise. Will report back when the build is done and tested for booting on nagara device. But that may happen tomorrow. Will remove report above as it was incorrect

**Comment by bartcubbins** [comment]
I was able to boot the device with r55 tag. I will test each platform, then prepare and PR patches
<details>
<summary>Photo</summary>
<img src="https://github.com/user-attachments/assets/666a19a7-e105-4db3-a574-b6812fc6f738"/> 
<details>

**Comment by EisregenHaha** [comment]
> I was able to boot the device with r55 tag. I will test each platform, then prepare and PR patches
> 
> Photo
> ![](https://private-user-images.githubusercontent.com/6766319/380917705-666a19a7-e105-4db3-a574-b6812fc6f738.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjc1NTgsIm5iZiI6MTczMDE2NzI1OCwicGF0aCI6Ii82NzY2MzE5LzM4MDkxNzcwNS02NjZhMTlhNy1lMTA1LTRkYjMtYTU3NC1iNjgxMmZjNmY3MzguSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMDIwMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBjYTdiOWNkYzRkN2JjYzcxNmZlMTVkYzYzNjAzMjJiYjIyYmJjOTdjNzllY2RlYzMwZTQ3NzczNjZlMjc2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kuOXxApSmpAin9gwkJjIj8j1d10qoJEpFAQ1MpwTreo)

thanks for the progress report, appreciate you keeping us in the loop

**Comment by rinigus** [comment]
hopefully irrelevant: r34 builds fine for nagara. haven't flashed it yet and cannot tell whether it boots

**Comment by ziggutas** [comment]
android-14.0.0_r34 builds without error in 5hrs. Device won't boot , sticks on the sony screen. 
I flashed the SW binaries v4a for yodo in fastbootd followed by all the partitions that have worked previously with android 13 and this device. I also included super empty.img on one attempt; no difference.
Doesn't rule out I'm not doing it right though.

The earliest stock 14 I have for preparing the device is 67.1.A.2.264 form August whereas this build is May. Might be a problem?

Is it OK to flash everything in fastbootd ? Don't seem to encounter this on other devices and quite often it's half and half; rebooting fastboot partway throught the installation.

Afterwards I also tried fastboot flashall in the build env but that's never worked for aosp and this device whereas it does for pixel8 and calyxos. Here's the log for that: https://pastebin.com/dRpZ6pKJ

Thanks again for the support and I look forward to trying the update when it's ready.

**Comment by EisregenHaha** [comment]
> android-14.0.0_r34 builds without error in 5hrs. Device won't boot , sticks on the sony screen. I flashed the SW binaries v4a for yodo in fastbootd followed by all the partitions that have worked previously with android 13 and this device. I also included super empty.img on one attempt; no difference. Doesn't rule out I'm not doing it right though.
> 
> The earliest stock 14 I have for preparing the device is 67.1.A.2.264 form August whereas this build is May. Might be a problem?
> 
> Is it OK to flash everything in fastbootd ? Don't seem to encounter this on other devices and quite often it's half and half; rebooting fastboot partway throught the installation.
> 
> Afterwards I also tried fastboot flashall in the build env but that's never worked for aosp and this device whereas it does for pixel8 and calyxos. Here's the log for that: https://pastebin.com/dRpZ6pKJ
> 
> Thanks again for the support and I look forward to trying the update when it's ready.

im pretty sure software binaries are flashed in fastboot not fastbootd, could be wrong tho. i also dont know if it even makes a difference. sad to hear though

**Comment by ziggutas** [comment]
> > android-14.0.0_r34 builds without error in 5hrs. Device won't boot , sticks on the sony screen. I flashed the SW binaries v4a for yodo in fastbootd followed by all the partitions that have worked previously with android 13 and this device. I also included super empty.img on one attempt; no difference. Doesn't rule out I'm not doing it right though.
> > The earliest stock 14 I have for preparing the device is 67.1.A.2.264 form August whereas this build is May. Might be a problem?
> > Is it OK to flash everything in fastbootd ? Don't seem to encounter this on other devices and quite often it's half and half; rebooting fastboot partway throught the installation.
> > Afterwards I also tried fastboot flashall in the build env but that's never worked for aosp and this device whereas it does for pixel8 and calyxos. Here's the log for that: https://pastebin.com/dRpZ6pKJ
> > Thanks again for the support and I look forward to trying the update when it's ready.
> 
> im pretty sure software binaries are flashed in fastboot not fastbootd, could be wrong tho. i also dont know if it even makes a difference. sad to hear though

**Comment by rinigus** [comment]
> im pretty sure software binaries are flashed in fastboot not fastbootd, could be wrong tho. i also dont know if it even makes a difference. sad to hear though

Based on https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-14 , part 6, we have to enter fastbootd before flashing (parts 7 and 8). 

Looking at the pastebin, it doesn't seem to include flashing oem image nor several others.

**Comment by EisregenHaha** [comment]
why would you close this issue while we are still discussing stuff lmao

**Comment by ziggutas** [comment]
Whoops! Sorry, was that me?

**Comment by ziggutas** [comment]
> > im pretty sure software binaries are flashed in fastboot not fastbootd, could be wrong tho. i also dont know if it even makes a difference. sad to hear though
> 
> Based on https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-14 , part 6, we have to enter fastbootd before flashing (parts 7 and 8). That way it worked for AOSP13
> 
> Looking at the pastebin, it doesn't seem to include flashing oem image nor several others.
> 
> PS: probably you flashed images before manually

Yes. Previously flashed everything in fastbootd. https://pastebin.com/nykg6wUb

**Comment by ziggutas** [comment]
> why would you close this issue while we are still discussing stuff lmao

Ha ha, sorry about that. Since we are discussing things maybe you can shed some light? Does getting a booting aosp build help to make it more likely for custom rom being available for a device? And if so, how ?

**Comment by EisregenHaha** [comment]
> > why would you close this issue while we are still discussing stuff lmao
> 
> Ha ha, sorry about that. Since we are discussing things maybe you can shed some light? Does getting a booting aosp build help to make it more likely for custom rom being available for a device? And if so, how ?

custom roms are compiled just like aosp, you will need to do basic bringup and for lineage roms also import quite a bit of stuff but generally if the tree (the stuff you cloned) boots on aosp it will also boot on aospish custom roms. but nobody will make a custom rom with these trees anyway rn, the devs in the xperia telegram are working on doing it properly i.e use a non prebuilt vendor etc. they dont want stuff precompiled but i dont really care which is why i tried statix. didnt boot ofc

**Comment by rinigus** [comment]
> android-14.0.0_r34 builds without error in 5hrs. Device won't boot , sticks on the sony screen.
I flashed the SW binaries v4a for yodo in fastbootd followed by all the partitions that have worked previously with android 13 and this device.

Same with Nagara - stuck on SONY logo with r34. So, we would have to wait for r55 patches

**Comment by bartcubbins** [comment]
I sent patches. You can use r55 or r67 when they land. So far, we have not received Android 14 ODM, we need to patch `android.hardware.security.keymint-service-qti` if we want to boot with Android 13 ODM. I can't provide you with a patched binary, but I can guide you how to do it yourself.
First you need a `patchelf` utility or something. Then follow these steps:
```
adb root
adb shell mount /dev/block/by-name/oem_a odm
adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti 
adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
adb reboot
```

**Comment by bartcubbins** [comment]
Maybe I missed something and some changes remained locally, please let me know if something goes wrong

**Comment by rinigus** [comment]
@bartcubbins, thank you very much! I managed to successfully boot AOSP14 using your patches and patchingandroid.hardware.security.keymint-service-qti . 

In addition, I had to patch common/hardware/health to get health service working. Will report regarding it separately.

Thats using Nagara 1iv

/cc @jerpelea

**Comment by bartcubbins** [comment]
Glad to hear! I think that after the release of the fresh ODM we can consider this case resolved.
Thanks for the report!

**Comment by EisregenHaha** [comment]
> Glad to hear! I think that after the release of the fresh ODM we can consider this case resolved. Thanks for the report!

thanks for pushing everything, will try 5V today

**Comment by EisregenHaha** [comment]
> > Glad to hear! I think that after the release of the fresh ODM we can consider this case resolved. Thanks for the report!
> 
> thanks for pushing everything, will try 5V today

@ziggutas are you still trying aosp? if yeah then i will sync statix to try that one again. if not/if you dont have time to test i'll sync aosp so would be great ti know

**Comment by EisregenHaha** [comment]
> Maybe I missed something and some changes remained locally, please let me know if something goes wrong

see since im building statix and not aosp i havent really reported bugs so far so let me know if this just statix exclusive but i got the error that vendor.qti.hardware.camera.aon wasnt in fcm, i had to add this into fcm in sony common

`    <hal format="hidl">
        <name>vendor.qti.hardware.camera.aon</name>
        <version>1.3</version>
        <interface>
            <name>IAONService</name>
            <instance>aoncameraservice</instance>
        </interface>
    </hal>`

if this is just on my side and a non aosp issue i apologize, just ignore in that case

**Comment by EisregenHaha** [comment]
> I sent patches. You can use r55 or r67 when they land. So far, we have not received Android 14 ODM, we need to patch `android.hardware.security.keymint-service-qti` if we want to boot with Android 13 ODM. I can't provide you with a patched binary, but I can guide you how to do it yourself. First you need a `patchelf` utility or something. Then follow these steps:
> 
> ```
> adb root
> adb shell mount /dev/block/by-name/oem_a odm
> adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
> patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti 
> adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
> adb reboot
> ```

also can i maybe ask when i need to enter these commands? when i do it on stock rom to extract the file i get the wrror that i cant even enter adb root since its a production build. after i install a magisk module which allows me to do so anyway i get the error: [eisregen@cachy statix]$ adb shell mount /dev/block/by-name/oem_a odm
mount: /dev/block/by-name/oem_a: need -t

**Comment by rinigus** [comment]
You can do it after you flash aosp with provided aosp blobs (from https://developer.sony.com/open-source/aosp-on-xperia-open-devices/downloads/software-binaries).

After flashing, reboot to recovery and then you probably can access it like that. 

Personally, I converted SW blob into raw image file on my linux pc, mounted it and changed on that raw image. Next, after unmounting, I made a new android sparse image and flashed that.

Good luck!

**Comment by EisregenHaha** [comment]
> You can do it after you flash aosp with provided aosp blobs (from https://developer.sony.com/open-source/aosp-on-xperia-open-devices/downloads/software-binaries).
> 
> After flashing, reboot to recovery and then you probably can access it like that.
> 
> Personally, I converted SW blob into raw image file on my linux pc, mounted it and changed on that raw image. Next, after unmounting, I made a new android sparse image and flashed that.
> 
> Good luck!

thanks i will try this because the command still keep failing for me, i cant even mount.

**Comment by EisregenHaha** [comment]
> You can do it after you flash aosp with provided aosp blobs (from https://developer.sony.com/open-source/aosp-on-xperia-open-devices/downloads/software-binaries).
> 
> After flashing, reboot to recovery and then you probably can access it like that.
> 
> Personally, I converted SW blob into raw image file on my linux pc, mounted it and changed on that raw image. Next, after unmounting, I made a new android sparse image and flashed that.
> 
> Good luck!

would you maybe give me a quick tut on how to do all tat? i tried but couldnt really find a way to convert the image like you said on arch, would appreciate if you could guide me

**Comment by ziggutas** [comment]
> see since im building statix and not aosp i havent really reported bugs so far so let me know if this just statix exclusive but i got the error that vendor.qti.hardware.camera.aon wasnt in fcm, i had to add this into fcm in sony common

Same error for aosp r67, thanks for the heads-up. I'll move on to attempting the flashing tomorrow.

**Comment by bartcubbins** [comment]
> adb root
> adb shell mount /dev/block/by-name/oem_a odm
> adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
> patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti 
> adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
> adb reboot

My bad. I missed to write what needs to be done in the AOSP recovery



> also can i maybe ask when i need to enter these commands?

Because this is a change and because we do not have AOSP 14 ODM...
https://android.googlesource.com/platform/hardware/interfaces/+/3a810627e0e104b4f93a39563c15f1b427250b82

**Comment by rinigus** [comment]
@EisregenHaha: you just have to find which package provides simg2img and reverse img2simg tools. On Gentoo its dev-util/android-tools

With these tools available, all you have to do is:

```
simg2img blob.img blob.raw
sudo mount blob.raw blob_folder
# change in blob_folder as root
sudo umount blob_folder
img2simg blob.raw blob-patched.img
```

and flash blob-patched. Please note that instructions above are written as I remember them. Hopefully, didn't miss anything.

**Comment by EisregenHaha** [comment]
> > adb root
> > adb shell mount /dev/block/by-name/oem_a odm
> > adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
> > patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti
> > adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
> > adb reboot
> 
> My bad. I missed to write what needs to be done in the AOSP recovery
> 
> > also can i maybe ask when i need to enter these commands?
> 
> Because this is a change and because we do not have AOSP 14 ODM... https://android.googlesource.com/platform/hardware/interfaces/+/3a810627e0e104b4f93a39563c15f1b427250b82

yeah i understand _why_, i was just confused about the _where_ since i got errors in system, and i still get the same doing them in the recovery. im gonna give up on the adb pull approach and just try the one described by ringus

**Comment by EisregenHaha** [comment]
> @EisregenHaha: you just have to find which package provides simg2img and reverse img2simg tools. On Gentoo its dev-util/android-tools
> 
> With these tools available, all you have to do is:
> 
> ```
> simg2img blob.img blob.raw
> sudo mount blob.raw blob_folder
> # change in blob_folder as root
> sudo umount blob_folder
> img2simg blob.raw blob-patched.img
> ```
> 
> and flash blob-patched. Please note that instructions above are written as I remember them. Hopefully, didn't miss anything.

thanks for these detailed instructions, i completely forgot that those commands existed. it worked like a charm. still doesnt boot but at this point im taking the L and trying aosp instead of custom roms lol

**Comment by ziggutas** [comment]
> I sent patches. You can use r55 or r67 when they land. So far, we have not received Android 14 ODM, we need to patch `android.hardware.security.keymint-service-qti` if we want to boot with Android 13 ODM. I can't provide you with a patched binary, but I can guide you how to do it yourself. First you need a `patchelf` utility or something. Then follow these steps:
> 
> ```
> adb root
> adb shell mount /dev/block/by-name/oem_a odm
> adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
> patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti 
> adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
> adb reboot
> ```

Build completes aosp r67 for pdx237 yodo after fixing error that vendor.qti.hardware.camera.aon wasnt in fcm. Manually added it into  sony common fcm same as here  https://github.com/sonyxperiadev/bug_tracker/issues/848#issuecomment-2455509265

I can complete the patching steps in recovery; device hangs on Sony screen.

**Comment by EisregenHaha** [comment]
> > I sent patches. You can use r55 or r67 when they land. So far, we have not received Android 14 ODM, we need to patch `android.hardware.security.keymint-service-qti` if we want to boot with Android 13 ODM. I can't provide you with a patched binary, but I can guide you how to do it yourself. First you need a `patchelf` utility or something. Then follow these steps:
> > ```
> > adb root
> > adb shell mount /dev/block/by-name/oem_a odm
> > adb pull /odm/bin/hw/android.hardware.security.keymint-service-qti
> > patchelf --add-needed android.hardware.security.rkp-V3-ndk.so android.hardware.security.keymint-service-qti 
> > adb push android.hardware.security.keymint-service-qti /odm/bin/hw/
> > adb reboot
> > ```
> 
> Build completes aosp r67 for pdx237 yodo after fixing error that vendor.qti.hardware.camera.aon wasnt in fcm. Manually added it into sony common fcm same as here [#848 (comment)](https://github.com/sonyxperiadev/bug_tracker/issues/848#issuecomment-2455509265)
> 
> I can complete the patching steps in recovery; device hangs on Sony screen.

for me its a bit different, i built aosp now and the device immediately turns off after the sony logo. it simply bootloops. 5V seems to be broken @bartcubbins

**Comment by EisregenHaha** [comment]
> I was able to boot the device with r55 tag. I will test each platform, then prepare and PR patches
> Photo
> ![](https://private-user-images.githubusercontent.com/6766319/380917705-666a19a7-e105-4db3-a574-b6812fc6f738.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDc4MDYsIm5iZiI6MTczMDgwNzUwNiwicGF0aCI6Ii82NzY2MzE5LzM4MDkxNzcwNS02NjZhMTlhNy1lMTA1LTRkYjMtYTU3NC1iNjgxMmZjNmY3MzguSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTE1MTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBmY2FkMzk1Y2ZmYzVlNGY4NDcxNTI5MTAxYWNkMjdjNmE3MGI5MGYyNDRiZTcwZjQwNjAwYmI0OGZiMjhlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fXrOoFhvJkayto94dp_1S40MEwb5yquEbGDcIDsHzEw)

seems like even your 1V build didnt have working baseband

**Comment by ziggutas** [comment]
@EisregenHaha  I'm maybe not understanding where to find the needed android.hardware.security.rkp-V3-ndk.so
When I search for it there appears a long list of files with that name in out/target for pdx237. Which one, or does it  matter? There are differing file sizes to add to my confusion.

Also, I'm now trying the direct method of mounting the .img to do this. Which folder would it go into?

**Comment by EisregenHaha** [comment]
> @EisregenHaha I'm maybe not understanding where to find the needed android.hardware.security.rkp-V3-ndk.so When I search for it there appears a long list of files with that name in out/target for pdx237. Which one, or does it matter? There are differing file sizes to add to my confusion.
> 
> Also, I'm now trying the direct method of mounting the .img to do this. Which folder would it go into?

the file is not in out, its in the firmware which we need to flash. i would recommend maybe no trying to use the manual method as it failed to boot for me till i managed to perform the commands. but if you want to then you will find the file in the bin/hw folder after mounting the raw iso

**Comment by ziggutas** [comment]
> > @EisregenHaha I'm maybe not understanding where to find the needed android.hardware.security.rkp-V3-ndk.so When I search for it there appears a long list of files with that name in out/target for pdx237. Which one, or does it matter? There are differing file sizes to add to my confusion.
> > Also, I'm now trying the direct method of mounting the .img to do this. Which folder would it go into?
> 
> the file is not in out, its in the firmware which we need to flash. i would recommend maybe no trying to use the manual method as it failed to boot for me till i managed to perform the commands. but if you want to then you will find the file in the bin/hw folder after mounting the raw iso. although i just went back to stock as the amount of bugs is insane, no keyboard until you sideload a different one, no sim recognized, audio settings c rash, no 120hz etc

Yeah I wasn't expecting a daily driver out of this; sounds exactly like my aosp13 experience on this device. But I've come this far so...

With blob.raw mounted I navigated into bin/hw folder, then to  "# change in blob_folder as root" I used the patchelf command. Then pack it up and flashed to make no difference.

Might be time to call it a day as well.

**Comment by bartcubbins** [comment]
The ticket was originally about compilation issues, please don't mix all the bugs in one ticket. It becomes very difficult to track them all. Let's create a ticket for each issue.
Thank you very much for your understanding!

**Comment by EisregenHaha** [comment]
> The ticket was originally about compilation issues, please don't mix all the bugs in one ticket. It becomes very difficult to track them all. Let's create a ticket for each issue. Thank you very much for your understanding!

yeah sorry about that, if i ever give it another shot i will but i probably will just give up now

**Comment by bartcubbins** [comment]
Sometimes I give up too. I do my best with the OSS part, but sometimes it seems pointless

**Comment by jerpelea** [comment]
I will close this ticket 
please open separate tickets for each problem
