### ISSUE TITLE
[Yoshino][Lilac] Open Camera app can't take pictures

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#402]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.174-gd7ab313501f1
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.014237
**Version baseband:** 1308-8921_47.1.A.16.20

**Description**
I have tried taking photos with the Open Camera app (time: 07:32). The Open Camera isn't able to take resp. save the taken photos. I have tried both front and main camera. I have checked that I have granted all required rights for Open Camera. 

In contrast the AOSP Camera app just works fine.
 
Not so sure whether this is a Open Camera bug or an AOSP bug since I haven't tried on Stock-ROM but I will double check on Stock-ROM as well later.

After I have tried taking photos with open camera I dumped the dmesg and also saved the logcat:
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3176010/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3176011/logcat.log)

**Symptoms**
Taking photos with open camera is not possible.

**How to reproduce**
Install Open Camera and try to take a photo it will not work.

**Comment by jerpelea** [comment]
the bug was fixed yesterday 
please recompile your kernel

**Comment by stefanhh0** [comment]
I have tested it this morning in on the latest kernel commit (d7ab313501f1) a fresh build that included all the changes that have been integrated yesterday. There it is not working.

I will double check on Stock-ROM later whether it is working or not there. Maybe you can have a second look if there is still something open?

**Comment by jerpelea** [comment]
I will recheck it after suzu

**Comment by stefanhh0** [comment]
Okay cool thanks I've seen you have pushed an additional "Revert msm:camera" commit today, I'll retest on a fresh/clean build.

**Comment by stefanhh0** [comment]
I have retested it on a fresh uptodate build (on latest kernel commit 6f8c28697397):
**Kernel version:** 4.9.174-g6f8c28697397
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.stefan.20190514.185903

Tried to take a photo and no photo was saved with open camera using camera v2 api.
I have saved dmesg and also logcat from that attempt and found following in the dmesg:

```
[  410.845533] msm_cam_smmu soc:qcom,cam_smmu:msm_cam_smmu_cb4: No iommu associated with device
[  410.845750] msm_jpeg_attach_iommu: Device attach failed
[  410.845792] msm_jpeg_platform_init: iommu attach failed
[  410.845908] __msm_jpeg_open:760] platform_init fail -19
[  411.593808] msm_cam_smmu soc:qcom,cam_smmu:msm_cam_smmu_cb5: No iommu associated with device
[  411.594034] msm_jpegdma caa0000.qcom,jpeg: Can not attach smmu.
[  411.594118] msm_jpegdma caa0000.qcom,jpeg: QBuf fail
```
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3180515/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3180514/logcat.log)

Should the bug then be reopened until it is fixed? I can't open it myself again...

**Comment by jerpelea** [comment]
I tested the camera on lilac and it works fine 
what kernel modification did you do ?

**Comment by wyzco** [comment]
Tried compiling the issues but it keeps failing, @stefanhh0 could you assist me with my compilation errors.
My telegram contact is [https://t.me/Wyzco](https://t.me/Wyzco) or you could suggest a messaging medium of your choice.

**Comment by stefanhh0** [comment]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.176-gf0356fa3bcac:
- https://github.com/sonyxperiadev/kernel/commit/39a85fa2d0ac283af82b383542fa1e88744a9d36
- Kernel PR 2261

**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v6_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200510.170705

Open camera is still not working on k1.14 but AOSP camera works okay, so practically the same situation as on k4.9 but maybe the reason is different why the camera is not working.

Following seen in logcat:
```
grep -w E logcat.log|grep 8122 
05-12 06:13:13.383  8122  8158 E ion     : ioctl c0044901 failed with code -1: Not a typewriter
05-12 06:13:34.507  8122  8122 E Camera  : Error 1
05-12 06:13:34.507  8122  8122 E CameraController1: camera onError: 1
05-12 06:13:34.507  8122  8122 E CameraController1:     CAMERA_ERROR_UNKNOWN 
```

[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4613352/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4613353/logcat.log)

@haxk20 you wanted me to test something newer? Please advice, don't remember what it was...

**Comment by Haxk20** [comment]
You will have to update to the new camera Hal.

**Comment by stefanhh0** [comment]
I postpone testing the new hal until the problems reported in #580 has been mitigated. I don't want to open too many construction sites at the same time on my phone :-)

Since dmesg I have posted was not right from start I have retestet it  on the default k4.14 camera hal not on the new one you want to have tested. 

Full logcat and dmesg when taking a photo with open camera:
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4648337/dmesg.log)
[logact.log](https://github.com/sonyxperiadev/bug_tracker/files/4648338/logact.log)

Shortly after having done the photo ran into a crash/reboot:
[console-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4648340/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4648341/dmesg-ramoops-0.log)
[dmesg-ramoops-1.log](https://github.com/sonyxperiadev/bug_tracker/files/4648343/dmesg-ramoops-1.log)
[pmsg-ramoops-0.log](https://github.com/sonyxperiadev/bug_tracker/files/4648344/pmsg-ramoops-0.log)

But that might be probably more related to the sensors issue in #580, since the call traces look more like coming from that direction.

**Comment by stefanhh0** [comment]
Fixed with the GA of v7 software binaries on kernel 4.14:

Verified using:
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.176-gbf769a2fc861
**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v7a_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200524.123100
